name = "actual-transaction-worker"
main = "src/index.js"
compatibility_date = "2024-05-24"

[vars]
OPENAI_KEY=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
OPENAI_ORG=org-YI06bweqJ9ZwGVyTYe3X1TaP
TG_BOT_TOKEN=8267155122:AAE9LsrqBc-tMzKge2GqdqGCeIZsioDsS6U
TG_CHAT_ID=1194216846
TG_SECRET_TOKEN=
ACTUAL_API_KEY=31a69feede0034113a9259cfa31396fc
ACTUAL_ENCRYPTION_PASSWORD=geekback
ACTUAL_BASE=http:///http://37.27.18.247:5007/v1/budgets/5e3d0cb1-b508-49fe-a0ca-f9a3610be5a8
