name = "actual-transaction-worker"
main = "src/index.js"
compatibility_date = "2024-05-24"

[vars]
OPENAI_KEY="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"
OPENAI_API_KEY="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"
OPENAI_ORG="org-YI06bweqJ9ZwGVyTYe3X1TaP"
TG_BOT_TOKEN="8267155122:AAE9LsrqBc-tMzKge2GqdqGCeIZsioDsS6U"
TG_CHAT_ID="1194216846"
ACTUAL_API_KEY="31a69feede0034113a9259cfa31396fc"
ACTUAL_ENCRYPTION_PASSWORD="geekback"
ACTUAL_BASE="http://actualbudget.zhoudream.com/v1/budgets/5e3d0cb1-b508-49fe-a0ca-f9a3610be5a8"

[observability]
enabled = true
head_sampling_rate = 1 # optional. default = 1.
