name = "actual-transaction-worker"
main = "src/index.js"
compatibility_date = "2024-05-24"

[vars]
OPENAI_KEY="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"
OPENAI_API_KEY="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"
OPENAI_ORG="org-YI06bweqJ9ZwGVyTYe3X1TaP"
TG_BOT_TOKEN="8267155122:AAE9LsrqBc-tMzKge2GqdqGCeIZsioDsS6U"
TG_CHAT_ID="1194216846"
ACTUAL_API_KEY="31a69feede0034113a9259cfa31396fc"
ACTUAL_ENCRYPTION_PASSWORD="geekback"
ACTUAL_BASE="http://37.27.18.247:5007/v1/budgets/5e3d0cb1-b508-49fe-a0ca-f9a3610be5a8"

[observability]
enabled = true
head_sampling_rate = 1 # optional. default = 1.
